version: '3'

volumes:
  {%- if instigator_py.database_engine == 'postgresql' %}
  {{ instigator_py.project_slug }}_local_postgres_data: {}
  {{ instigator_py.project_slug }}_local_postgres_data_backups: {}
  {{ instigator_py.project_slug }}_local_pgadmin: {}
  {%- endif %}
  {%- if instigator_py.database_engine == 'mysql' %}
  {{ instigator_py.project_slug }}_local_mysql_data: {}
  {{ instigator_py.project_slug }}_local_mysql_data_backups: {}
  {%- endif %}

services:
  django:{% if instigator_py.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ instigator_py.project_slug }}_local_django
    container_name: {{ instigator_py.project_slug }}_local_django
    {%- if instigator_py.database_engine == 'mysql' %}
    links:
      - mysql
    {%- endif %}
    depends_on:
      {%- if instigator_py.database_engine == 'postgresql' %}
      - postgres
      {%- endif %}
      {%- if instigator_py.database_engine == 'mysql' %}
      - mysql
      {%- endif %}
      {%- if instigator_py.use_celery == 'y' %}
      - redis
      {%- endif %}
      {%- if instigator_py.use_mailhog == 'y' %}
      - mailhog
      {%- endif %}
      {%- if instigator_py.use_selenium == 'y' %}
      - selenium
      {%- endif %}
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      {%- if instigator_py.database_engine == 'postgresql' %}
      - ./.envs/.local/.postgres
      {%- endif %}
      {%- if instigator_py.database_engine == 'mysql' %}
      - ./.envs/.local/.mysql
      {%- endif %}
    ports:
      - '8000:8000'
    command: /start

  {%- if instigator_py.database_engine == 'postgresql' %}
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ instigator_py.project_slug }}_production_postgres
    container_name: {{ instigator_py.project_slug }}_local_postgres
    ports:
      - '5432:5432'
    volumes:
      - {{ instigator_py.project_slug }}_local_postgres_data:/var/lib/postgresql/data
      - {{ instigator_py.project_slug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: {{ instigator_py.project_slug }}_local_pgadmin
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - {{ instigator_py.project_slug }}_local_pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - '5050:80'
  {%- endif %}
  {%- if instigator_py.database_engine == 'mysql' %}
  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: {{ instigator_py.project_slug }}_production_mysql
    container_name: mysql
    volumes:
      - {{ instigator_py.project_slug }}_local_mysql_data:/var/lib/mysql
      - {{ instigator_py.project_slug }}_local_mysql_data_backups:/backups
    env_file:
      - ./.envs/.local/.mysql
    ports:
      - '3406:3306'
  {%- endif %}

  docs:
    image: {{ instigator_py.project_slug }}_local_docs
    container_name: {{ instigator_py.project_slug }}_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./{{ instigator_py.project_slug }}:/app/{{ instigator_py.project_slug }}:z
    ports:
      - '9000:9000'
    command: /start-docs
  {%- if instigator_py.use_mailhog == 'y' %}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: {{ instigator_py.project_slug }}_local_mailhog
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if instigator_py.use_celery == 'y' %}

  redis:
    image: redis:6
    container_name: {{ instigator_py.project_slug }}_local_redis

  celeryworker:
    <<: *django
    image: {{ instigator_py.project_slug }}_local_celeryworker
    container_name: {{ instigator_py.project_slug }}_local_celeryworker
    depends_on:
      - redis
      {%- if instigator_py.database_engine == 'postgresql' %}
      - postgres
      {%- endif %}
      {%- if instigator_py.database_engine == 'mysql' %}
      - mysql
      {%- endif %}
      {%- if instigator_py.use_mailhog == 'y' %}
      - mailhog
      {%- endif %}
      {%- if instigator_py.use_selenium == 'y' %}
      - selenium
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ instigator_py.project_slug }}_local_celerybeat
    container_name: {{ instigator_py.project_slug }}_local_celerybeat
    depends_on:
      - redis
      {%- if instigator_py.database_engine == 'postgresql' %}
      - postgres
      {%- endif %}
      {%- if instigator_py.database_engine == 'mysql' %}
      - mysql
      {%- endif %}
      {%- if instigator_py.use_mailhog == 'y' %}
      - mailhog
      {%- endif %}
      {%- if instigator_py.use_selenium == 'y' %}
      - selenium
      {%- endif %}
    ports: []
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ instigator_py.project_slug }}_local_flower
    container_name: {{ instigator_py.project_slug }}_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  {%- endif %}
  {%- if instigator_py.frontend_pipeline in ['Gulp', 'Webpack'] %}

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ instigator_py.project_slug }}_local_node
    container_name: {{ instigator_py.project_slug }}_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      {%- if instigator_py.frontend_pipeline == 'Gulp' %}
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
      {%- endif %}

  {%- endif %}
  {%- if instigator_py.use_selenium == 'y' %}
  selenium:
    image: seleniarm/standalone-chromium
    container_name: {{ instigator_py.project_slug }}_local_selenium
    ports:
      - '4444:4444'
  {%- endif %}
